import IISFlexberrybooksclubMeetingplanEController from '../i-i-s-flexberrybooksclub-meetingplan-e';

var IISFlexberrybooksclubMeetingplanENewController = IISFlexberrybooksclubMeetingplanEController;
export default IISFlexberrybooksclubMeetingplanENewController;
