//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Flexberrybooksclub
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Book.
    /// </summary>
    //  *** Start programmer edit section *** (Book CustomAttributes)

    //  *** End programmer edit section *** (Book CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("BookE", new string[] {
            "tittle as \'Tittle\'",
            "author as \'Author\'",
            "pages as \'Pages\'",
            "coverURL as \'Cover URL\'",
            "descriptionURL as \'Description URL\'",
            "tags as \'Tags\'",
            "score as \'Score\'"})]
    [View("BookL", new string[] {
            "tittle as \'Tittle\'",
            "author as \'Author\'",
            "pages as \'Pages\'",
            "coverURL as \'Cover URL\'",
            "descriptionURL as \'Description URL\'",
            "tags as \'Tags\'",
            "score as \'Score\'"})]
    public class Book : ICSSoft.STORMNET.DataObject
    {
        
        private string ftittle;
        
        private string fauthor;
        
        private int fpages;
        
        private string fcoverURL;
        
        private string fdescriptionURL;
        
        private string ftags;
        
        private double fscore;
        
        //  *** Start programmer edit section *** (Book CustomMembers)

        //  *** End programmer edit section *** (Book CustomMembers)

        
        /// <summary>
        /// tittle.
        /// </summary>
        //  *** Start programmer edit section *** (Book.tittle CustomAttributes)

        //  *** End programmer edit section *** (Book.tittle CustomAttributes)
        [StrLen(255)]
        public virtual string tittle
        {
            get
            {
                //  *** Start programmer edit section *** (Book.tittle Get start)

                //  *** End programmer edit section *** (Book.tittle Get start)
                string result = this.ftittle;
                //  *** Start programmer edit section *** (Book.tittle Get end)

                //  *** End programmer edit section *** (Book.tittle Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.tittle Set start)

                //  *** End programmer edit section *** (Book.tittle Set start)
                this.ftittle = value;
                //  *** Start programmer edit section *** (Book.tittle Set end)

                //  *** End programmer edit section *** (Book.tittle Set end)
            }
        }
        
        /// <summary>
        /// author.
        /// </summary>
        //  *** Start programmer edit section *** (Book.author CustomAttributes)

        //  *** End programmer edit section *** (Book.author CustomAttributes)
        [StrLen(255)]
        public virtual string author
        {
            get
            {
                //  *** Start programmer edit section *** (Book.author Get start)

                //  *** End programmer edit section *** (Book.author Get start)
                string result = this.fauthor;
                //  *** Start programmer edit section *** (Book.author Get end)

                //  *** End programmer edit section *** (Book.author Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.author Set start)

                //  *** End programmer edit section *** (Book.author Set start)
                this.fauthor = value;
                //  *** Start programmer edit section *** (Book.author Set end)

                //  *** End programmer edit section *** (Book.author Set end)
            }
        }
        
        /// <summary>
        /// pages.
        /// </summary>
        //  *** Start programmer edit section *** (Book.pages CustomAttributes)

        //  *** End programmer edit section *** (Book.pages CustomAttributes)
        public virtual int pages
        {
            get
            {
                //  *** Start programmer edit section *** (Book.pages Get start)

                //  *** End programmer edit section *** (Book.pages Get start)
                int result = this.fpages;
                //  *** Start programmer edit section *** (Book.pages Get end)

                //  *** End programmer edit section *** (Book.pages Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.pages Set start)

                //  *** End programmer edit section *** (Book.pages Set start)
                this.fpages = value;
                //  *** Start programmer edit section *** (Book.pages Set end)

                //  *** End programmer edit section *** (Book.pages Set end)
            }
        }
        
        /// <summary>
        /// coverURL.
        /// </summary>
        //  *** Start programmer edit section *** (Book.coverURL CustomAttributes)

        //  *** End programmer edit section *** (Book.coverURL CustomAttributes)
        [StrLen(255)]
        public virtual string coverURL
        {
            get
            {
                //  *** Start programmer edit section *** (Book.coverURL Get start)

                //  *** End programmer edit section *** (Book.coverURL Get start)
                string result = this.fcoverURL;
                //  *** Start programmer edit section *** (Book.coverURL Get end)

                //  *** End programmer edit section *** (Book.coverURL Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.coverURL Set start)

                //  *** End programmer edit section *** (Book.coverURL Set start)
                this.fcoverURL = value;
                //  *** Start programmer edit section *** (Book.coverURL Set end)

                //  *** End programmer edit section *** (Book.coverURL Set end)
            }
        }
        
        /// <summary>
        /// descriptionURL.
        /// </summary>
        //  *** Start programmer edit section *** (Book.descriptionURL CustomAttributes)

        //  *** End programmer edit section *** (Book.descriptionURL CustomAttributes)
        [StrLen(255)]
        public virtual string descriptionURL
        {
            get
            {
                //  *** Start programmer edit section *** (Book.descriptionURL Get start)

                //  *** End programmer edit section *** (Book.descriptionURL Get start)
                string result = this.fdescriptionURL;
                //  *** Start programmer edit section *** (Book.descriptionURL Get end)

                //  *** End programmer edit section *** (Book.descriptionURL Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.descriptionURL Set start)

                //  *** End programmer edit section *** (Book.descriptionURL Set start)
                this.fdescriptionURL = value;
                //  *** Start programmer edit section *** (Book.descriptionURL Set end)

                //  *** End programmer edit section *** (Book.descriptionURL Set end)
            }
        }
        
        /// <summary>
        /// tags.
        /// </summary>
        //  *** Start programmer edit section *** (Book.tags CustomAttributes)

        //  *** End programmer edit section *** (Book.tags CustomAttributes)
        [StrLen(255)]
        public virtual string tags
        {
            get
            {
                //  *** Start programmer edit section *** (Book.tags Get start)

                //  *** End programmer edit section *** (Book.tags Get start)
                string result = this.ftags;
                //  *** Start programmer edit section *** (Book.tags Get end)

                //  *** End programmer edit section *** (Book.tags Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.tags Set start)

                //  *** End programmer edit section *** (Book.tags Set start)
                this.ftags = value;
                //  *** Start programmer edit section *** (Book.tags Set end)

                //  *** End programmer edit section *** (Book.tags Set end)
            }
        }
        
        /// <summary>
        /// score.
        /// </summary>
        //  *** Start programmer edit section *** (Book.score CustomAttributes)

        //  *** End programmer edit section *** (Book.score CustomAttributes)
        public virtual double score
        {
            get
            {
                //  *** Start programmer edit section *** (Book.score Get start)

                //  *** End programmer edit section *** (Book.score Get start)
                double result = this.fscore;
                //  *** Start programmer edit section *** (Book.score Get end)

                //  *** End programmer edit section *** (Book.score Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.score Set start)

                //  *** End programmer edit section *** (Book.score Set start)
                this.fscore = value;
                //  *** Start programmer edit section *** (Book.score Set end)

                //  *** End programmer edit section *** (Book.score Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "BookE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BookE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BookE", typeof(IIS.Flexberrybooksclub.Book));
                }
            }
            
            /// <summary>
            /// "BookL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BookL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BookL", typeof(IIS.Flexberrybooksclub.Book));
                }
            }
        }
    }
}
