//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Flexberrybooksclub
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Meetingrequest.
    /// </summary>
    //  *** Start programmer edit section *** (Meetingrequest CustomAttributes)

    //  *** End programmer edit section *** (Meetingrequest CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("MeetingrequestE", new string[] {
            "requestdate as \'Requestdate\'",
            "Speaker as \'Speaker\'",
            "Speaker.surname as \'Surname\'",
            "Book as \'Book\'",
            "Book.tittle as \'Tittle\'"}, Hidden=new string[] {
            "Speaker.surname",
            "Book.tittle"})]
    [MasterViewDefineAttribute("MeetingrequestE", "Speaker", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "surname")]
    [MasterViewDefineAttribute("MeetingrequestE", "Book", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "tittle")]
    public class Meetingrequest : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime frequestdate;
        
        private IIS.Flexberrybooksclub.Speaker fSpeaker;
        
        private IIS.Flexberrybooksclub.Book fBook;
        
        private IIS.Flexberrybooksclub.Meetingplan fMeetingplan;
        
        //  *** Start programmer edit section *** (Meetingrequest CustomMembers)

        //  *** End programmer edit section *** (Meetingrequest CustomMembers)

        
        /// <summary>
        /// requestdate.
        /// </summary>
        //  *** Start programmer edit section *** (Meetingrequest.requestdate CustomAttributes)

        //  *** End programmer edit section *** (Meetingrequest.requestdate CustomAttributes)
        public virtual System.DateTime requestdate
        {
            get
            {
                //  *** Start programmer edit section *** (Meetingrequest.requestdate Get start)

                //  *** End programmer edit section *** (Meetingrequest.requestdate Get start)
                System.DateTime result = this.frequestdate;
                //  *** Start programmer edit section *** (Meetingrequest.requestdate Get end)

                //  *** End programmer edit section *** (Meetingrequest.requestdate Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Meetingrequest.requestdate Set start)

                //  *** End programmer edit section *** (Meetingrequest.requestdate Set start)
                this.frequestdate = value;
                //  *** Start programmer edit section *** (Meetingrequest.requestdate Set end)

                //  *** End programmer edit section *** (Meetingrequest.requestdate Set end)
            }
        }
        
        /// <summary>
        /// Meetingrequest.
        /// </summary>
        //  *** Start programmer edit section *** (Meetingrequest.Speaker CustomAttributes)

        //  *** End programmer edit section *** (Meetingrequest.Speaker CustomAttributes)
        [NotNull()]
        public virtual IIS.Flexberrybooksclub.Speaker Speaker
        {
            get
            {
                //  *** Start programmer edit section *** (Meetingrequest.Speaker Get start)

                //  *** End programmer edit section *** (Meetingrequest.Speaker Get start)
                IIS.Flexberrybooksclub.Speaker result = this.fSpeaker;
                //  *** Start programmer edit section *** (Meetingrequest.Speaker Get end)

                //  *** End programmer edit section *** (Meetingrequest.Speaker Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Meetingrequest.Speaker Set start)

                //  *** End programmer edit section *** (Meetingrequest.Speaker Set start)
                this.fSpeaker = value;
                //  *** Start programmer edit section *** (Meetingrequest.Speaker Set end)

                //  *** End programmer edit section *** (Meetingrequest.Speaker Set end)
            }
        }
        
        /// <summary>
        /// Meetingrequest.
        /// </summary>
        //  *** Start programmer edit section *** (Meetingrequest.Book CustomAttributes)

        //  *** End programmer edit section *** (Meetingrequest.Book CustomAttributes)
        [NotNull()]
        public virtual IIS.Flexberrybooksclub.Book Book
        {
            get
            {
                //  *** Start programmer edit section *** (Meetingrequest.Book Get start)

                //  *** End programmer edit section *** (Meetingrequest.Book Get start)
                IIS.Flexberrybooksclub.Book result = this.fBook;
                //  *** Start programmer edit section *** (Meetingrequest.Book Get end)

                //  *** End programmer edit section *** (Meetingrequest.Book Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Meetingrequest.Book Set start)

                //  *** End programmer edit section *** (Meetingrequest.Book Set start)
                this.fBook = value;
                //  *** Start programmer edit section *** (Meetingrequest.Book Set end)

                //  *** End programmer edit section *** (Meetingrequest.Book Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Flexberrybooksclub.Meetingplan.
        /// </summary>
        //  *** Start programmer edit section *** (Meetingrequest.Meetingplan CustomAttributes)

        //  *** End programmer edit section *** (Meetingrequest.Meetingplan CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Flexberrybooksclub.Meetingplan Meetingplan
        {
            get
            {
                //  *** Start programmer edit section *** (Meetingrequest.Meetingplan Get start)

                //  *** End programmer edit section *** (Meetingrequest.Meetingplan Get start)
                IIS.Flexberrybooksclub.Meetingplan result = this.fMeetingplan;
                //  *** Start programmer edit section *** (Meetingrequest.Meetingplan Get end)

                //  *** End programmer edit section *** (Meetingrequest.Meetingplan Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Meetingrequest.Meetingplan Set start)

                //  *** End programmer edit section *** (Meetingrequest.Meetingplan Set start)
                this.fMeetingplan = value;
                //  *** Start programmer edit section *** (Meetingrequest.Meetingplan Set end)

                //  *** End programmer edit section *** (Meetingrequest.Meetingplan Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "MeetingrequestE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MeetingrequestE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MeetingrequestE", typeof(IIS.Flexberrybooksclub.Meetingrequest));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Meetingrequest.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfMeetingrequest CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfMeetingrequest CustomAttributes)
    public class DetailArrayOfMeetingrequest : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.Flexberrybooksclub.DetailArrayOfMeetingrequest members)

        //  *** End programmer edit section *** (IIS.Flexberrybooksclub.DetailArrayOfMeetingrequest members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Meetingrequest by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Meetingrequest.
        /// </summary>
        public DetailArrayOfMeetingrequest(IIS.Flexberrybooksclub.Meetingplan fMeetingplan) : 
                base(typeof(Meetingrequest), ((ICSSoft.STORMNET.DataObject)(fMeetingplan)))
        {
        }
        
        public IIS.Flexberrybooksclub.Meetingrequest this[int index]
        {
            get
            {
                return ((IIS.Flexberrybooksclub.Meetingrequest)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Flexberrybooksclub.Meetingrequest dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
