//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Flexberrybooksclub
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Meetingplan.
    /// </summary>
    //  *** Start programmer edit section *** (Meetingplan CustomAttributes)

    //  *** End programmer edit section *** (Meetingplan CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("MeetingplanE", new string[] {
            "plandate as \'Plandate\'"})]
    [AssociatedDetailViewAttribute("MeetingplanE", "Meetingrequest", "MeetingrequestE", true, "", "Meetingrequest", true, new string[] {
            ""})]
    [View("MeetingplanL", new string[] {
            "plandate as \'Plandate\'"})]
    public class Meetingplan : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fplandate;
        
        private IIS.Flexberrybooksclub.DetailArrayOfMeetingrequest fMeetingrequest;
        
        //  *** Start programmer edit section *** (Meetingplan CustomMembers)

        //  *** End programmer edit section *** (Meetingplan CustomMembers)

        
        /// <summary>
        /// plandate.
        /// </summary>
        //  *** Start programmer edit section *** (Meetingplan.plandate CustomAttributes)

        //  *** End programmer edit section *** (Meetingplan.plandate CustomAttributes)
        public virtual System.DateTime plandate
        {
            get
            {
                //  *** Start programmer edit section *** (Meetingplan.plandate Get start)

                //  *** End programmer edit section *** (Meetingplan.plandate Get start)
                System.DateTime result = this.fplandate;
                //  *** Start programmer edit section *** (Meetingplan.plandate Get end)

                //  *** End programmer edit section *** (Meetingplan.plandate Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Meetingplan.plandate Set start)

                //  *** End programmer edit section *** (Meetingplan.plandate Set start)
                this.fplandate = value;
                //  *** Start programmer edit section *** (Meetingplan.plandate Set end)

                //  *** End programmer edit section *** (Meetingplan.plandate Set end)
            }
        }
        
        /// <summary>
        /// Meetingplan.
        /// </summary>
        //  *** Start programmer edit section *** (Meetingplan.Meetingrequest CustomAttributes)

        //  *** End programmer edit section *** (Meetingplan.Meetingrequest CustomAttributes)
        public virtual IIS.Flexberrybooksclub.DetailArrayOfMeetingrequest Meetingrequest
        {
            get
            {
                //  *** Start programmer edit section *** (Meetingplan.Meetingrequest Get start)

                //  *** End programmer edit section *** (Meetingplan.Meetingrequest Get start)
                if ((this.fMeetingrequest == null))
                {
                    this.fMeetingrequest = new IIS.Flexberrybooksclub.DetailArrayOfMeetingrequest(this);
                }
                IIS.Flexberrybooksclub.DetailArrayOfMeetingrequest result = this.fMeetingrequest;
                //  *** Start programmer edit section *** (Meetingplan.Meetingrequest Get end)

                //  *** End programmer edit section *** (Meetingplan.Meetingrequest Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Meetingplan.Meetingrequest Set start)

                //  *** End programmer edit section *** (Meetingplan.Meetingrequest Set start)
                this.fMeetingrequest = value;
                //  *** Start programmer edit section *** (Meetingplan.Meetingrequest Set end)

                //  *** End programmer edit section *** (Meetingplan.Meetingrequest Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "MeetingplanE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MeetingplanE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MeetingplanE", typeof(IIS.Flexberrybooksclub.Meetingplan));
                }
            }
            
            /// <summary>
            /// "MeetingplanL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MeetingplanL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MeetingplanL", typeof(IIS.Flexberrybooksclub.Meetingplan));
                }
            }
        }
    }
}
