//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Flexberrybooksclub
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Meeting.
    /// </summary>
    //  *** Start programmer edit section *** (Meeting CustomAttributes)

    //  *** End programmer edit section *** (Meeting CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("MeetingE", new string[] {
            "meetingdate as \'Meetingdate\'"})]
    [AssociatedDetailViewAttribute("MeetingE", "Report", "ReportE", true, "", "Report", true, new string[] {
            ""})]
    [View("MeetingL", new string[] {
            "meetingdate as \'Meetingdate\'"})]
    public class Meeting : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fmeetingdate;
        
        private IIS.Flexberrybooksclub.DetailArrayOfReport fReport;
        
        //  *** Start programmer edit section *** (Meeting CustomMembers)

        //  *** End programmer edit section *** (Meeting CustomMembers)

        
        /// <summary>
        /// meetingdate.
        /// </summary>
        //  *** Start programmer edit section *** (Meeting.meetingdate CustomAttributes)

        //  *** End programmer edit section *** (Meeting.meetingdate CustomAttributes)
        public virtual System.DateTime meetingdate
        {
            get
            {
                //  *** Start programmer edit section *** (Meeting.meetingdate Get start)

                //  *** End programmer edit section *** (Meeting.meetingdate Get start)
                System.DateTime result = this.fmeetingdate;
                //  *** Start programmer edit section *** (Meeting.meetingdate Get end)

                //  *** End programmer edit section *** (Meeting.meetingdate Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Meeting.meetingdate Set start)

                //  *** End programmer edit section *** (Meeting.meetingdate Set start)
                this.fmeetingdate = value;
                //  *** Start programmer edit section *** (Meeting.meetingdate Set end)

                //  *** End programmer edit section *** (Meeting.meetingdate Set end)
            }
        }
        
        /// <summary>
        /// Meeting.
        /// </summary>
        //  *** Start programmer edit section *** (Meeting.Report CustomAttributes)

        //  *** End programmer edit section *** (Meeting.Report CustomAttributes)
        public virtual IIS.Flexberrybooksclub.DetailArrayOfReport Report
        {
            get
            {
                //  *** Start programmer edit section *** (Meeting.Report Get start)

                //  *** End programmer edit section *** (Meeting.Report Get start)
                if ((this.fReport == null))
                {
                    this.fReport = new IIS.Flexberrybooksclub.DetailArrayOfReport(this);
                }
                IIS.Flexberrybooksclub.DetailArrayOfReport result = this.fReport;
                //  *** Start programmer edit section *** (Meeting.Report Get end)

                //  *** End programmer edit section *** (Meeting.Report Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Meeting.Report Set start)

                //  *** End programmer edit section *** (Meeting.Report Set start)
                this.fReport = value;
                //  *** Start programmer edit section *** (Meeting.Report Set end)

                //  *** End programmer edit section *** (Meeting.Report Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "MeetingE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MeetingE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MeetingE", typeof(IIS.Flexberrybooksclub.Meeting));
                }
            }
            
            /// <summary>
            /// "MeetingL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MeetingL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MeetingL", typeof(IIS.Flexberrybooksclub.Meeting));
                }
            }
        }
    }
}
