//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Flexberrybooksclub
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Report.
    /// </summary>
    //  *** Start programmer edit section *** (Report CustomAttributes)

    //  *** End programmer edit section *** (Report CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ReportE", new string[] {
            "reportdate as \'Reportdate\'",
            "booklevel as \'Booklevel\'",
            "presentationURL as \'Presentation URL\'",
            "videoURL as \'Video URL\'",
            "review as \'Review\'",
            "Speaker as \'Speaker\'",
            "Speaker.surname as \'Surname\'",
            "Book as \'Book\'",
            "Book.tittle as \'Tittle\'"}, Hidden=new string[] {
            "Speaker.surname",
            "Book.tittle"})]
    [MasterViewDefineAttribute("ReportE", "Speaker", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "surname")]
    [MasterViewDefineAttribute("ReportE", "Book", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "tittle")]
    public class Report : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime freportdate;
        
        private string fvideoURL;
        
        private int fbooklevel;
        
        private string fpresentationURL;
        
        private string freview;
        
        private IIS.Flexberrybooksclub.Speaker fSpeaker;
        
        private IIS.Flexberrybooksclub.Book fBook;
        
        private IIS.Flexberrybooksclub.Meeting fMeeting;
        
        //  *** Start programmer edit section *** (Report CustomMembers)

        //  *** End programmer edit section *** (Report CustomMembers)

        
        /// <summary>
        /// reportdate.
        /// </summary>
        //  *** Start programmer edit section *** (Report.reportdate CustomAttributes)

        //  *** End programmer edit section *** (Report.reportdate CustomAttributes)
        public virtual System.DateTime reportdate
        {
            get
            {
                //  *** Start programmer edit section *** (Report.reportdate Get start)

                //  *** End programmer edit section *** (Report.reportdate Get start)
                System.DateTime result = this.freportdate;
                //  *** Start programmer edit section *** (Report.reportdate Get end)

                //  *** End programmer edit section *** (Report.reportdate Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Report.reportdate Set start)

                //  *** End programmer edit section *** (Report.reportdate Set start)
                this.freportdate = value;
                //  *** Start programmer edit section *** (Report.reportdate Set end)

                //  *** End programmer edit section *** (Report.reportdate Set end)
            }
        }
        
        /// <summary>
        /// videoURL.
        /// </summary>
        //  *** Start programmer edit section *** (Report.videoURL CustomAttributes)

        //  *** End programmer edit section *** (Report.videoURL CustomAttributes)
        [StrLen(255)]
        public virtual string videoURL
        {
            get
            {
                //  *** Start programmer edit section *** (Report.videoURL Get start)

                //  *** End programmer edit section *** (Report.videoURL Get start)
                string result = this.fvideoURL;
                //  *** Start programmer edit section *** (Report.videoURL Get end)

                //  *** End programmer edit section *** (Report.videoURL Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Report.videoURL Set start)

                //  *** End programmer edit section *** (Report.videoURL Set start)
                this.fvideoURL = value;
                //  *** Start programmer edit section *** (Report.videoURL Set end)

                //  *** End programmer edit section *** (Report.videoURL Set end)
            }
        }
        
        /// <summary>
        /// booklevel.
        /// </summary>
        //  *** Start programmer edit section *** (Report.booklevel CustomAttributes)

        //  *** End programmer edit section *** (Report.booklevel CustomAttributes)
        public virtual int booklevel
        {
            get
            {
                //  *** Start programmer edit section *** (Report.booklevel Get start)

                //  *** End programmer edit section *** (Report.booklevel Get start)
                int result = this.fbooklevel;
                //  *** Start programmer edit section *** (Report.booklevel Get end)

                //  *** End programmer edit section *** (Report.booklevel Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Report.booklevel Set start)

                //  *** End programmer edit section *** (Report.booklevel Set start)
                this.fbooklevel = value;
                //  *** Start programmer edit section *** (Report.booklevel Set end)

                //  *** End programmer edit section *** (Report.booklevel Set end)
            }
        }
        
        /// <summary>
        /// presentationURL.
        /// </summary>
        //  *** Start programmer edit section *** (Report.presentationURL CustomAttributes)

        //  *** End programmer edit section *** (Report.presentationURL CustomAttributes)
        [StrLen(255)]
        public virtual string presentationURL
        {
            get
            {
                //  *** Start programmer edit section *** (Report.presentationURL Get start)

                //  *** End programmer edit section *** (Report.presentationURL Get start)
                string result = this.fpresentationURL;
                //  *** Start programmer edit section *** (Report.presentationURL Get end)

                //  *** End programmer edit section *** (Report.presentationURL Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Report.presentationURL Set start)

                //  *** End programmer edit section *** (Report.presentationURL Set start)
                this.fpresentationURL = value;
                //  *** Start programmer edit section *** (Report.presentationURL Set end)

                //  *** End programmer edit section *** (Report.presentationURL Set end)
            }
        }
        
        /// <summary>
        /// review.
        /// </summary>
        //  *** Start programmer edit section *** (Report.review CustomAttributes)

        //  *** End programmer edit section *** (Report.review CustomAttributes)
        [StrLen(255)]
        public virtual string review
        {
            get
            {
                //  *** Start programmer edit section *** (Report.review Get start)

                //  *** End programmer edit section *** (Report.review Get start)
                string result = this.freview;
                //  *** Start programmer edit section *** (Report.review Get end)

                //  *** End programmer edit section *** (Report.review Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Report.review Set start)

                //  *** End programmer edit section *** (Report.review Set start)
                this.freview = value;
                //  *** Start programmer edit section *** (Report.review Set end)

                //  *** End programmer edit section *** (Report.review Set end)
            }
        }
        
        /// <summary>
        /// Report.
        /// </summary>
        //  *** Start programmer edit section *** (Report.Speaker CustomAttributes)

        //  *** End programmer edit section *** (Report.Speaker CustomAttributes)
        [NotNull()]
        public virtual IIS.Flexberrybooksclub.Speaker Speaker
        {
            get
            {
                //  *** Start programmer edit section *** (Report.Speaker Get start)

                //  *** End programmer edit section *** (Report.Speaker Get start)
                IIS.Flexberrybooksclub.Speaker result = this.fSpeaker;
                //  *** Start programmer edit section *** (Report.Speaker Get end)

                //  *** End programmer edit section *** (Report.Speaker Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Report.Speaker Set start)

                //  *** End programmer edit section *** (Report.Speaker Set start)
                this.fSpeaker = value;
                //  *** Start programmer edit section *** (Report.Speaker Set end)

                //  *** End programmer edit section *** (Report.Speaker Set end)
            }
        }
        
        /// <summary>
        /// Report.
        /// </summary>
        //  *** Start programmer edit section *** (Report.Book CustomAttributes)

        //  *** End programmer edit section *** (Report.Book CustomAttributes)
        [NotNull()]
        public virtual IIS.Flexberrybooksclub.Book Book
        {
            get
            {
                //  *** Start programmer edit section *** (Report.Book Get start)

                //  *** End programmer edit section *** (Report.Book Get start)
                IIS.Flexberrybooksclub.Book result = this.fBook;
                //  *** Start programmer edit section *** (Report.Book Get end)

                //  *** End programmer edit section *** (Report.Book Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Report.Book Set start)

                //  *** End programmer edit section *** (Report.Book Set start)
                this.fBook = value;
                //  *** Start programmer edit section *** (Report.Book Set end)

                //  *** End programmer edit section *** (Report.Book Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Flexberrybooksclub.Meeting.
        /// </summary>
        //  *** Start programmer edit section *** (Report.Meeting CustomAttributes)

        //  *** End programmer edit section *** (Report.Meeting CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Flexberrybooksclub.Meeting Meeting
        {
            get
            {
                //  *** Start programmer edit section *** (Report.Meeting Get start)

                //  *** End programmer edit section *** (Report.Meeting Get start)
                IIS.Flexberrybooksclub.Meeting result = this.fMeeting;
                //  *** Start programmer edit section *** (Report.Meeting Get end)

                //  *** End programmer edit section *** (Report.Meeting Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Report.Meeting Set start)

                //  *** End programmer edit section *** (Report.Meeting Set start)
                this.fMeeting = value;
                //  *** Start programmer edit section *** (Report.Meeting Set end)

                //  *** End programmer edit section *** (Report.Meeting Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ReportE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ReportE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ReportE", typeof(IIS.Flexberrybooksclub.Report));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Report.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfReport CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfReport CustomAttributes)
    public class DetailArrayOfReport : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.Flexberrybooksclub.DetailArrayOfReport members)

        //  *** End programmer edit section *** (IIS.Flexberrybooksclub.DetailArrayOfReport members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Report by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Report.
        /// </summary>
        public DetailArrayOfReport(IIS.Flexberrybooksclub.Meeting fMeeting) : 
                base(typeof(Report), ((ICSSoft.STORMNET.DataObject)(fMeeting)))
        {
        }
        
        public IIS.Flexberrybooksclub.Report this[int index]
        {
            get
            {
                return ((IIS.Flexberrybooksclub.Report)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Flexberrybooksclub.Report dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
