//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Flexberrybooksclub
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Speaker.
    /// </summary>
    //  *** Start programmer edit section *** (Speaker CustomAttributes)

    //  *** End programmer edit section *** (Speaker CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SpeakerE", new string[] {
            "surname as \'Surname\'",
            "firstname as \'Firstname\'",
            "secondname as \'Secondname\'"})]
    [View("SpeakerL", new string[] {
            "surname as \'Surname\'",
            "firstname as \'Firstname\'",
            "secondname as \'Secondname\'"})]
    public class Speaker : ICSSoft.STORMNET.DataObject
    {
        
        private string fsurname;
        
        private string ffirstname;
        
        private string fsecondname;
        
        //  *** Start programmer edit section *** (Speaker CustomMembers)

        //  *** End programmer edit section *** (Speaker CustomMembers)

        
        /// <summary>
        /// surname.
        /// </summary>
        //  *** Start programmer edit section *** (Speaker.surname CustomAttributes)

        //  *** End programmer edit section *** (Speaker.surname CustomAttributes)
        [StrLen(255)]
        public virtual string surname
        {
            get
            {
                //  *** Start programmer edit section *** (Speaker.surname Get start)

                //  *** End programmer edit section *** (Speaker.surname Get start)
                string result = this.fsurname;
                //  *** Start programmer edit section *** (Speaker.surname Get end)

                //  *** End programmer edit section *** (Speaker.surname Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Speaker.surname Set start)

                //  *** End programmer edit section *** (Speaker.surname Set start)
                this.fsurname = value;
                //  *** Start programmer edit section *** (Speaker.surname Set end)

                //  *** End programmer edit section *** (Speaker.surname Set end)
            }
        }
        
        /// <summary>
        /// firstname.
        /// </summary>
        //  *** Start programmer edit section *** (Speaker.firstname CustomAttributes)

        //  *** End programmer edit section *** (Speaker.firstname CustomAttributes)
        [StrLen(255)]
        public virtual string firstname
        {
            get
            {
                //  *** Start programmer edit section *** (Speaker.firstname Get start)

                //  *** End programmer edit section *** (Speaker.firstname Get start)
                string result = this.ffirstname;
                //  *** Start programmer edit section *** (Speaker.firstname Get end)

                //  *** End programmer edit section *** (Speaker.firstname Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Speaker.firstname Set start)

                //  *** End programmer edit section *** (Speaker.firstname Set start)
                this.ffirstname = value;
                //  *** Start programmer edit section *** (Speaker.firstname Set end)

                //  *** End programmer edit section *** (Speaker.firstname Set end)
            }
        }
        
        /// <summary>
        /// secondname.
        /// </summary>
        //  *** Start programmer edit section *** (Speaker.secondname CustomAttributes)

        //  *** End programmer edit section *** (Speaker.secondname CustomAttributes)
        [StrLen(255)]
        public virtual string secondname
        {
            get
            {
                //  *** Start programmer edit section *** (Speaker.secondname Get start)

                //  *** End programmer edit section *** (Speaker.secondname Get start)
                string result = this.fsecondname;
                //  *** Start programmer edit section *** (Speaker.secondname Get end)

                //  *** End programmer edit section *** (Speaker.secondname Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Speaker.secondname Set start)

                //  *** End programmer edit section *** (Speaker.secondname Set start)
                this.fsecondname = value;
                //  *** Start programmer edit section *** (Speaker.secondname Set end)

                //  *** End programmer edit section *** (Speaker.secondname Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SpeakerE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SpeakerE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SpeakerE", typeof(IIS.Flexberrybooksclub.Speaker));
                }
            }
            
            /// <summary>
            /// "SpeakerL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SpeakerL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SpeakerL", typeof(IIS.Flexberrybooksclub.Speaker));
                }
            }
        }
    }
}
